--
-- http://www.dummies.com/how-to/content/how-to-unplug-and-plug-in-your-pluggable-database-.html
-- http://oracle-base.com/articles/12c/multitenant-create-and-configure-pluggable-database-12cr1.php#manual-unplug-pdb
--
